import datetime
import os
import re
import smtplib
from email.message import EmailMessage
from html import escape

_SEVERITY_COLORS = {"critical": "#c62828", "warning": "#ef6c00"}
_TS_FORMAT = "%Y-%m-%d %H:%M:%SZ"


def send_escalation(subject, body, html=None):
    """Email the on-call contact. Returns a status string; never raises."""
    host = os.getenv("SMTP_HOST")
    to_addr = os.getenv("ALERT_EMAIL_TO")
    if not host or not to_addr:
        return "email not configured (set SMTP_HOST and ALERT_EMAIL_TO)"

    port = int(os.getenv("SMTP_PORT", "587"))
    user = os.getenv("SMTP_USER")
    password = os.getenv("SMTP_PASSWORD")
    from_addr = os.getenv("ALERT_EMAIL_FROM") or user or "argus@localhost"

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.set_content(body)
    if html:
        msg.add_alternative(html, subtype="html")

    try:
        if port == 465:
            server = smtplib.SMTP_SSL(host, port, timeout=10)
        else:
            server = smtplib.SMTP(host, port, timeout=10)
            if os.getenv("SMTP_STARTTLS", "1") != "0":
                server.starttls()
        with server:
            if user and password:
                server.login(user, password)
            server.send_message(msg)
    except Exception as e:
        return f"email failed: {e}"
    return f"email sent to {to_addr}"


def describe_action(tool, args):
    service = args.get("service", "the service")
    return {
        "restart_pod": f"Restart all pods of `{service}` (brief disruption while new pods start).",
        "rollback_deployment": f"Roll `{service}` back to its previous revision.",
        "scale_deployment": f"Scale `{service}` to {args.get('replicas', '?')} replicas.",
    }.get(tool, f"Run `{tool}`.")


def format_duration(start, end):
    try:
        secs = int((datetime.datetime.strptime(end, _TS_FORMAT) - datetime.datetime.strptime(start, _TS_FORMAT)).total_seconds())
    except (ValueError, TypeError):
        return "unknown"
    secs = max(secs, 0)
    if secs < 60:
        return f"{secs}s"
    if secs < 3600:
        return f"{secs // 60}m {secs % 60}s"
    return f"{secs // 3600}h {secs % 3600 // 60}m"


def _markdown_to_html(text):
    out, in_list = [], False
    for raw in text.splitlines():
        line = escape(raw.strip())
        line = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
        if line.startswith("- "):
            if not in_list:
                out.append("<ul style='margin:4px 0 8px 18px;padding:0'>")
                in_list = True
            out.append(f"<li>{line[2:]}</li>")
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        if line.startswith("## "):
            out.append(f"<div style='font-weight:600;margin-top:10px;color:#1a237e'>{line[3:]}</div>")
        elif line:
            out.append(f"<div style='margin:2px 0'>{line}</div>")
    if in_list:
        out.append("</ul>")
    return "".join(out)


def _section(title, inner):
    return (
        f"<div style='margin-top:18px'>"
        f"<div style='font-size:12px;letter-spacing:.08em;color:#607d8b;font-weight:700;"
        f"border-bottom:1px solid #eceff1;padding-bottom:4px;margin-bottom:8px'>{title}</div>{inner}</div>"
    )


def _pre(s):
    return (
        "<pre style='background:#f5f7f8;border:1px solid #eceff1;border-radius:4px;padding:10px;"
        "font-size:12px;white-space:pre-wrap;margin:0'>" + escape((s or "(not captured)")[:1500]) + "</pre>"
    )


def _kv(label, value):
    return (
        f"<td style='padding:6px 16px 6px 0;vertical-align:top'>"
        f"<div style='font-size:11px;color:#78909c'>{label}</div>"
        f"<div style='font-size:14px;font-weight:600'>{escape(str(value))}</div></td>"
    )


def _banner(color, kicker, title):
    return (
        f"<div style='background:{color};color:#fff;padding:14px 18px;border-radius:6px 6px 0 0'>"
        f"<div style='font-size:12px;letter-spacing:.1em'>{kicker}</div>"
        f"<div style='font-size:20px;font-weight:700;margin-top:2px'>{title}</div></div>"
    )


def _wrap(banner, body):
    return (
        "<div style=\"font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;max-width:680px;margin:auto;color:#263238\">"
        f"{banner}<div style='border:1px solid #eceff1;border-top:0;padding:16px 18px;border-radius:0 0 6px 6px'>{body}"
        "<div style='margin-top:20px;font-size:11px;color:#90a4ae'>Generated by ARGUS &mdash; "
        "Autonomous Reasoning Gateway for Unified Systems</div></div></div>"
    )


def build_incident_email(inc):
    """Escalation email: an action was rejected or timed out. Returns (subject, plain_text, html)."""
    severity = (inc.get("severity") or "unknown").lower()
    color = _SEVERITY_COLORS.get(severity, "#546e7a")
    outcome = inc["outcome"]
    action = f"{inc['tool_name']} {inc['args']}"
    subject = f"[{inc['id']}] {severity.upper()} - {inc['service']}: {outcome}"

    text = "\n".join([
        f"{inc['id']}  |  Severity: {severity.upper()}  |  Status: OPEN - action required",
        f"Service: {inc['service']}   Namespace: {inc['namespace']}   Detected (UTC): {inc['detected_at']}",
        "",
        f"ACTION {outcome}: {action}",
        "No changes were made. A human must act.",
        "",
        "ALERT", inc["alert_text"] or "(not captured)",
        "",
        "IMPACT (metrics snapshot)", inc["metrics_text"] or "(not captured)",
        "",
        "ARGUS DIAGNOSIS", inc["diagnosis"] or "(none)",
        "",
        "PROPOSED CHANGE (dry-run)", inc["dry_output"],
        "",
        "Generated by ARGUS - Autonomous Reasoning Gateway for Unified Systems",
    ])

    body = (
        f"<table style='border-collapse:collapse'><tr>"
        f"{_kv('Service', inc['service'])}{_kv('Namespace', inc['namespace'])}"
        f"{_kv('Detected (UTC)', inc['detected_at'])}{_kv('Status', 'OPEN')}</tr></table>"
        f"<div style='margin-top:12px;padding:10px 12px;background:#fff3e0;border-left:4px solid {color};border-radius:3px'>"
        f"<b>Action {escape(outcome)}.</b> ARGUS proposed <code>{escape(action)}</code>. "
        f"No changes were made &mdash; a human must act.</div>"
        f"{_section('ALERT', _pre(inc['alert_text']))}"
        f"{_section('IMPACT &mdash; METRICS SNAPSHOT', _pre(inc['metrics_text']))}"
        f"{_section('ARGUS DIAGNOSIS', _markdown_to_html(inc['diagnosis'] or '(none)'))}"
        f"{_section('PROPOSED CHANGE (DRY-RUN)', _pre(inc['dry_output']))}"
    )
    html = _wrap(_banner(color, "ARGUS INCIDENT ESCALATION", f"{escape(inc['id'])} &middot; {escape(severity.upper())}"), body)
    return subject, text, html


_OUTCOMES = {
    "resolved": ("#2e7d32", "#f1f8e9", "ARGUS INCIDENT CLOSED", "RESOLVED", "RESOLVED",
                 "Service recovered after the approved action. The alert stayed clear on consecutive checks."),
    "not_recovered": ("#c62828", "#ffebee", "ARGUS INCIDENT UPDATE", "ACTION REQUIRED", "ACTION REQUIRED",
                      "The approved action ran, but the alert is still firing. The incident remains open and needs a human."),
    "failed": ("#c62828", "#ffebee", "ARGUS INCIDENT UPDATE", "REMEDIATION FAILED", "ACTION REQUIRED",
               "The approved action failed to execute. The incident remains open and needs a human."),
}

_PAST_TENSE = {"restart_pod": "restarted", "rollback_deployment": "rolled back", "scale_deployment": "scaled"}


def build_resolution_email(inc):
    """Closure / follow-up email after an approved remediation. inc['outcome'] is resolved | not_recovered | failed."""
    color, tint, kicker, label, status, headline = _OUTCOMES[inc["outcome"]]
    severity = (inc.get("severity") or "unknown").upper()
    action_plain = describe_action(inc["tool_name"], inc["args"]).replace("`", "")
    duration = format_duration(inc.get("firing_since"), inc.get("resolved_at")) if inc["outcome"] == "resolved" else "ongoing"
    done = _PAST_TENSE.get(inc["tool_name"], "remediated")
    subject = {
        "resolved": f"[{inc['id']}] RESOLVED - {inc['service']} {done}, alert cleared",
        "not_recovered": f"[{inc['id']}] ACTION REQUIRED - {inc['service']} {done}, alert still firing",
        "failed": f"[{inc['id']}] REMEDIATION FAILED - {inc['service']}",
    }[inc["outcome"]]

    text = "\n".join([
        f"{inc['id']}  |  {label}  |  Severity: {severity}",
        headline,
        "",
        f"Service: {inc['service']}   Namespace: {inc['namespace']}",
        f"Firing since (UTC): {inc.get('firing_since')}   Detected by ARGUS: {inc.get('detected_at')}",
        f"Resolved (UTC): {inc.get('resolved_at') or '-'}   Total duration: {duration}",
        "",
        "SUMMARY", inc.get("summary") or "(not available)",
        "",
        "ACTION TAKEN (approved by operator)", action_plain,
        "",
        "RESULT", inc.get("action_result") or "(none)",
        "",
        "ROOT CAUSE (ARGUS)", inc.get("root_cause") or "(not captured)",
        "",
        "METRICS BEFORE", inc.get("metrics_before") or "(not captured)",
        "",
        "METRICS AFTER", inc.get("metrics_after") or "(not captured)",
        "",
        "Generated by ARGUS - Autonomous Reasoning Gateway for Unified Systems",
    ])

    body = (
        f"<table style='border-collapse:collapse'><tr>"
        f"{_kv('Service', inc['service'])}{_kv('Namespace', inc['namespace'])}"
        f"{_kv('Status', status)}{_kv('Total duration', duration)}</tr><tr>"
        f"{_kv('Firing since (UTC)', inc.get('firing_since'))}{_kv('Detected by ARGUS', inc.get('detected_at'))}"
        f"{_kv('Resolved (UTC)', inc.get('resolved_at') or '-')}{_kv('Severity', severity)}</tr></table>"
        f"<div style='margin-top:12px;padding:10px 12px;background:{tint};border-left:4px solid {color};border-radius:3px'>"
        f"{escape(headline)}</div>"
        f"{_section('SUMMARY', _markdown_to_html(inc.get('summary') or '(not available)'))}"
        f"{_section('ACTION TAKEN (APPROVED BY OPERATOR)', f'<div>{escape(action_plain)}</div>')}"
        f"{_section('RESULT', _pre(inc.get('action_result')))}"
        f"{_section('ROOT CAUSE (ARGUS)', _markdown_to_html(inc.get('root_cause') or '(not captured)'))}"
        f"{_section('METRICS BEFORE', _pre(inc.get('metrics_before')))}"
        f"{_section('METRICS AFTER', _pre(inc.get('metrics_after')))}"
    )
    html = _wrap(_banner(color, kicker, f"{escape(inc['id'])} &middot; {escape(label)}"), body)
    return subject, text, html


def dashboard_url():
    return os.getenv("ARGUS_DASHBOARD_URL", "http://localhost:8501")


def _link_button(label):
    return (
        f"<div style='margin-top:16px'><a href='{escape(dashboard_url())}' style='display:inline-block;background:#1a237e;"
        f"color:#fff;text-decoration:none;padding:10px 18px;border-radius:4px;font-weight:600'>{escape(label)}</a>"
        f"<div style='font-size:11px;color:#90a4ae;margin-top:6px'>{escape(dashboard_url())}</div></div>"
    )


def build_detection_email(inc, auto):
    """Sent once when the watcher opens an incident. Returns (subject, plain_text, html)."""
    severity = (inc.get("severity") or "unknown").lower()
    color = _SEVERITY_COLORS.get(severity, "#546e7a")
    headline = ("ARGUS is investigating automatically. Nothing will be changed without operator approval."
                if auto else "No investigation has started. Open the dashboard and click Investigate.")
    subject = f"[{inc['id']}] DETECTED - {inc['service']}: {inc.get('summary') or inc['alertname']}"

    text = "\n".join([
        f"{inc['id']}  |  DETECTED  |  Severity: {severity.upper()}",
        headline,
        "",
        f"Alert: {inc['alertname']}",
        f"Service: {inc['service']}",
        f"Summary: {inc.get('summary') or '-'}",
        f"Firing since (UTC): {inc['active_at']}",
        "",
        f"Dashboard: {dashboard_url()}",
        "",
        "Generated by ARGUS - Autonomous Reasoning Gateway for Unified Systems",
    ])
    body = (
        f"<table style='border-collapse:collapse'><tr>"
        f"{_kv('Service', inc['service'])}{_kv('Alert', inc['alertname'])}"
        f"{_kv('Firing since (UTC)', inc['active_at'])}{_kv('Status', 'DETECTED')}</tr></table>"
        f"<div style='margin-top:12px;padding:10px 12px;background:#fff3e0;border-left:4px solid {color};border-radius:3px'>"
        f"<b>{escape(inc.get('summary') or inc['alertname'])}</b><br>{escape(headline)}</div>"
        f"{_link_button('Open in ARGUS')}"
    )
    html = _wrap(_banner(color, "ARGUS INCIDENT DETECTED", f"{escape(inc['id'])} &middot; {escape(severity.upper())}"), body)
    return subject, text, html


def build_approval_email(inc, tool, args, why, expires_utc, reminder=False):
    """Sent when ARGUS needs a decision (and again halfway through the wait as a reminder)."""
    action = describe_action(tool, args).replace("`", "")
    lead = "REMINDER - " if reminder else ""
    subject = f"[{inc['id']}] {lead}APPROVAL NEEDED - {action}"
    note = ("If nobody responds, ARGUS will not act: the request expires and the on-call contact is notified.")

    text = "\n".join([
        f"{inc['id']}  |  {lead}APPROVAL NEEDED  |  Service: {inc['service']}",
        "",
        f"ARGUS proposes: {action}",
        f"This request expires at {expires_utc} UTC. {note}",
        "",
        "WHY", why or "(see the dashboard)",
        "",
        f"Approve or reject here: {dashboard_url()}",
        "",
        "Generated by ARGUS - Autonomous Reasoning Gateway for Unified Systems",
    ])
    color = "#ef6c00"
    body = (
        f"<div style='padding:10px 12px;background:#fff3e0;border-left:4px solid {color};border-radius:3px'>"
        f"<b>ARGUS proposes:</b> {escape(action)}<br>"
        f"This request expires at <b>{escape(expires_utc)} UTC</b>. {escape(note)}</div>"
        f"{_section('WHY', _markdown_to_html(why or '(see the dashboard)'))}"
        f"{_link_button('Review and decide')}"
    )
    kicker = "ARGUS REMINDER" if reminder else "ARGUS ACTION REQUIRED"
    html = _wrap(_banner(color, kicker, f"{escape(inc['id'])} &middot; APPROVAL NEEDED"), body)
    return subject, text, html
